### ISSUE TITLE
Help setting up different db for logging

### ISSUE THREAD

**Issue by Rameshv** [customink/central_logger#14]
Hi,
  I am currently building the app with Mongoid. It seems that central-logger logs the data in default mongoid database, But i wanted to use different database for logging. How can i do this.?

Cheers

**Comment by chmurph2** [comment]
@rameshv,

You can specify which database Central Logger uses in your database.yml or central_logger.yml configuration file.  Please see the README for the details: https://github.com/customink/central_logger/blob/master/README.md

-Chris
