### ISSUE TITLE
undefined method `mongo_connection` for Log4r

### ISSUE THREAD

**Issue by tispratik** [customink/central_logger#17]
Does central logger have support for log4r?

```
ruby-1.8.7-p352 :001 > db = Rails.logger.mongo_connection
NoMethodError: undefined method `mongo_connection' for #<Log4r::Logger:0x105092850>
```

**Comment by astupka** [comment]
I've never tested it with Log4r.  It should replace the logger when the railtie is loaded and run at boot time.  I suspect the logger is being set to the log4r logger instead of the MongoLogger.   

What version of Rails are you running?

**Comment by tispratik** [comment]
Right, the rails logger is being replaced by Log4r logger. I am using Rails 2.

**Comment by astupka** [comment]
Because I am replacing the logger, I don't think you will be able to use the functionality in log4r without doing the same to the log4r logger class or creating a CentralLoggerOutputter the log4r class could add to its chain of outputters.

**Comment by tispratik** [comment]
Oh ok, right. I am new to log4r too, but i understand what you're referring to. Can you please tell me exactly how to create the outputter class?
