### ISSUE TITLE
logging stopped working on heroku

### ISSUE THREAD

**Issue by jpines** [customink/central_logger#27]
Works just fine locally including in production environment to production logs. No code or gem changes on our end, no relevant Heroku changes we are aware of. Any ideas?

**Comment by jpines** [comment]
This is for "include: CentralLogger::Filter" in ApplicationController and we haven't changed any settings. Stopped working a week ago.

**Comment by jpines** [comment]
Need to disable rails_log_stdout plugin which Heroku automatically installs during push. Create vendor/plugins/rails_log_stdout and stick an empty file in it e.g. .gitignore.

**Comment by astupka** [comment]
Thanks for documenting how you fixed it. 

Alex
